"""Initial Migration

Revision ID: 374be2347f09
Revises: 
Create Date: 2025-05-12 22:27:59.526882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '374be2347f09'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_tiers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('stripe_price_id', sa.String(length=100), nullable=False),
    sa.Column('max_resumes', sa.Integer(), nullable=False),
    sa.Column('max_applications', sa.Integer(), nullable=False),
    sa.Column('monthly_interview_credits', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('phone_number', sa.String(length=12), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('interviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('company', sa.String(length=100), nullable=False),
    sa.Column('position', sa.String(length=100), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('conversation', sa.JSON(), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_app',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('company', sa.String(length=500), nullable=False),
    sa.Column('position', sa.String(length=250), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=False),
    sa.Column('application_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=200), nullable=True),
    sa.Column('contact_person', sa.String(length=200), nullable=True),
    sa.Column('contact_email', sa.String(length=250), nullable=True),
    sa.Column('phone_number', sa.String(length=12), nullable=True),
    sa.Column('interview_date', sa.DateTime(), nullable=True),
    sa.Column('interview_mode', sa.String(length=200), nullable=True),
    sa.Column('follow_up_date', sa.DateTime(), nullable=True),
    sa.Column('offer_date', sa.DateTime(), nullable=True),
    sa.Column('salary_offer', sa.Float(), nullable=True),
    sa.Column('job_type', sa.String(length=200), nullable=True),
    sa.Column('application_link', sa.String(length=5000), nullable=True),
    sa.Column('notes', sa.String(length=5000), nullable=True),
    sa.Column('result', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resume',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('phone_number', sa.String(length=12), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('skills', sa.String(length=500), nullable=False),
    sa.Column('analysis', sa.String(length=5000), nullable=True),
    sa.Column('optimized_version', sa.String(length=10000), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('tier_id', sa.String(length=36), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(length=100), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('remaining_interview_credits', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tier_id'], ['subscription_tiers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('certification',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('resume_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('issuer', sa.String(length=250), nullable=False),
    sa.Column('completed_date', sa.DateTime(), nullable=False),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('education_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('resume_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('school', sa.String(length=250), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('graduation_date', sa.DateTime(), nullable=True),
    sa.Column('in_progress', sa.Boolean(), nullable=False),
    sa.Column('achievements', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_experience',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('resume_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.String(length=100), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('is_present', sa.Boolean(), nullable=False),
    sa.Column('duties', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_experience')
    op.drop_table('education_history')
    op.drop_table('certification')
    op.drop_table('user_subscriptions')
    op.drop_table('resume')
    op.drop_table('job_app')
    op.drop_table('interviews')
    op.drop_table('user')
    op.drop_table('subscription_tiers')
    # ### end Alembic commands ###
