"""Updated Enums in DB to String

Revision ID: 8b3d9cb26c24
Revises: 
Create Date: 2025-05-12 11:46:55.325498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b3d9cb26c24'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_app', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('interview_mode',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('job_type',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('result',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_app', schema=None) as batch_op:
        batch_op.alter_column('result',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)
        batch_op.alter_column('job_type',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=9),
               existing_nullable=True)
        batch_op.alter_column('interview_mode',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=11),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=12),
               existing_nullable=True)

    # ### end Alembic commands ###
