"""Fixed Interview Model

Revision ID: c731dc44e5cd
Revises: 
Create Date: 2025-05-12 17:19:34.837411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c731dc44e5cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mock_interviews')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mock_interviews',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('company', sa.VARCHAR(length=100), nullable=False),
    sa.Column('position', sa.VARCHAR(length=100), nullable=False),
    sa.Column('experience_level', sa.VARCHAR(length=50), nullable=True),
    sa.Column('chat_transcript', sa.TEXT(), nullable=True),
    sa.Column('ai_feedback', sa.TEXT(), nullable=True),
    sa.Column('score_communication', sa.INTEGER(), nullable=True),
    sa.Column('score_content', sa.INTEGER(), nullable=True),
    sa.Column('score_confidence', sa.INTEGER(), nullable=True),
    sa.Column('total_score', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('resume_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
