"""Update Subscription Management with Grace Period & Downgrades

Revision ID: f9c346fe7465
Revises: 374be2347f09
Create Date: 2025-05-13 13:55:14.575999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9c346fe7465'
down_revision = '374be2347f09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grace_period_end', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_payment_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('next_payment_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_subscriptions', schema=None) as batch_op:
        batch_op.drop_column('next_payment_date')
        batch_op.drop_column('last_payment_date')
        batch_op.drop_column('grace_period_end')

    # ### end Alembic commands ###
